using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using PNet.Generators.Emit;
using PNet.Generators.Metadata;
using PNet.Generators.Model;

namespace PNet.Generators;

/// <summary>
/// Source generator that, at the p.net library's build time, reads the runtime's BCL
/// implementation DLLs and emits C# 14 extension-member wrappers for every private member
/// of every type in the configured target namespaces. The output compiles into PNet.dll —
/// users consume that pre-built library; no generator runs on their side.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ExtensionMembersGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targetNamespacesProvider = context.AnalyzerConfigOptionsProvider.Select(static (options, _) =>
        {
            if (options.GlobalOptions.TryGetValue("build_property.PNetTargetNamespaces", out var value)
                && !string.IsNullOrWhiteSpace(value))
            {
                return value.Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries)
                            .Select(s => s.Trim())
                            .Where(s => s.Length > 0)
                            .ToArray();
            }
            return Array.Empty<string>();
        });

        var combined = targetNamespacesProvider.Combine(context.CompilationProvider);

        context.RegisterSourceOutput(combined, static (spc, pair) =>
        {
            var targetNamespaces = pair.Left;
            var consumerCompilation = pair.Right;

            try
            {
                // Empty / missing PNetTargetNamespaces ⇒ scan every namespace in every runtime DLL.
                HashSet<string>? nsSet = targetNamespaces.Length == 0
                    ? null
                    : new HashSet<string>(targetNamespaces, StringComparer.Ordinal);

                var runtimePaths = RuntimeResolver.GetRuntimeImplAssemblies();
                var scanned = PeScanner.Scan(runtimePaths, nsSet, consumerCompilation);

                var typesByNamespace = new Dictionary<string, List<TypeModel>>(StringComparer.Ordinal);
                foreach (var type in scanned)
                {
                    if (!typesByNamespace.TryGetValue(type.Namespace, out var bucket))
                        typesByNamespace[type.Namespace] = bucket = new List<TypeModel>();
                    bucket.Add(type);
                }

                foreach (var kv in typesByNamespace)
                {
                    var ns = kv.Key;
                    var types = kv.Value;
                    if (types.Count == 0) continue;

                    var deduped = types
                        .GroupBy(t => t.TypeName + "`" + t.ArityCount)
                        .Select(g => g.First())
                        .OrderBy(t => t.TypeName)
                        .ToList();

                    // Emit one file per type so a compile error in one doesn't cascade across the namespace.
                    foreach (var type in deduped)
                    {
                        var source = ExtensionEmitter.Emit(ns, new[] { type });
                        // Skip files where the emitter produced no class body (every member was filtered).
                        if (source.IndexOf("public static class", StringComparison.Ordinal) < 0) continue;
                        var hint = "PNet." + ns.Replace('.', '_') + "." + type.TypeName + "_" + type.ArityCount + ".g.cs";
                        spc.AddSource(hint, SourceText.From(source, Encoding.UTF8));
                    }
                }

                // Emit a summary marker file so the user sees something got generated even if namespaces are empty.
                var summary = new StringBuilder();
                summary.AppendLine("// <auto-generated/>");
                int populated = 0;
                foreach (var kv in typesByNamespace) if (kv.Value.Count > 0) populated++;
                summary.Append("// p.net generated extensions for ").Append(populated).AppendLine(" namespaces:");
                foreach (var kv in typesByNamespace.OrderBy(kv2 => kv2.Key))
                    summary.Append("//   ").Append(kv.Key).Append(" — ").Append(kv.Value.Count).AppendLine(" types");
                spc.AddSource("PNet._Summary.g.cs", SourceText.From(summary.ToString(), Encoding.UTF8));
            }
            catch (Exception ex)
            {
                var desc = new DiagnosticDescriptor(
                    id: "PNET0101",
                    title: "p.net generator failure",
                    messageFormat: "p.net generator threw while scanning runtime DLLs: {0}",
                    category: "PNet",
                    defaultSeverity: DiagnosticSeverity.Error,
                    isEnabledByDefault: true);
                spc.ReportDiagnostic(Diagnostic.Create(desc, Location.None, ex.ToString()));
            }
        });
    }

}
