using System.Collections.Generic;
using System.Linq;
using System.Text;
using PNet.Generators.Model;

namespace PNet.Generators.Emit;

internal static class ExtensionEmitter
{
    private const string Inlining = "[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]";

    public static string Emit(string targetNamespace, IReadOnlyList<TypeModel> types)
    {
        var sb = new StringBuilder(16 * 1024);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by p.net — private .NET APIs as extension members.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0626 // extern without DllImport (UnsafeAccessor)");
        sb.AppendLine("#pragma warning disable CS8500 // sizeof/addressof for ref-like types");
        sb.AppendLine("#pragma warning disable CS0108 // hides inherited member");
        sb.AppendLine("#pragma warning disable CS0109 // no member found to hide");
        sb.AppendLine("#pragma warning disable CS0649 // never assigned");
        sb.AppendLine("#pragma warning disable CS8669 // nullable annotation outside nullable context");
        sb.AppendLine("#pragma warning disable CS8714 // notnull constraint mismatch");
        sb.AppendLine("#pragma warning disable CS9113 // unused primary-ctor parameter");
        sb.AppendLine();

        sb.Append("namespace PNet.").Append(targetNamespace).AppendLine();
        sb.AppendLine("{");
        foreach (var type in types.OrderBy(t => t.TypeName))
        {
            EmitTypeClass(sb, type);
            sb.AppendLine();
        }
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitTypeClass(StringBuilder sb, TypeModel type)
    {
        if (type.IsStatic) return;

        // Nothing emittable (only static members, or all instance members were filtered out)?
        // Skip the whole class — emitting an empty `_PrivateExtensions` stub creates a phantom
        // namespace in PNet.dll that has no actual extension surface.
        var instanceMembers = type.Members.Where(m => m.Kind is MemberKind.InstanceField or MemberKind.InstanceMethod).ToList();
        if (instanceMembers.Count == 0) return;

        var className = type.ArityCount > 0
            ? type.TypeName + "_" + type.ArityCount + "_PrivateExtensions"
            : type.TypeName + "_PrivateExtensions";
        sb.Append("public static class ").Append(className).AppendLine();
        sb.AppendLine("{");

        var targetGenericArgs = type.TypeParameterNames.Count == 0
            ? ""
            : "<" + string.Join(", ", type.TypeParameterNames) + ">";
        var targetDisplay = "global::" + type.Namespace + "." + type.TypeName + targetGenericArgs;

        // 1. Instance extensions under `extension<T...>(TargetType<T...> @this)` block
        {
            sb.Append("    extension");
            if (type.TypeParameterNames.Count > 0)
                sb.Append('<').Append(string.Join(", ", type.TypeParameterNames)).Append('>');
            sb.Append('(').Append(targetDisplay).Append(" @this)");
            AppendConstraints(sb, type.TypeParameterConstraints);
            sb.AppendLine();
            sb.AppendLine("    {");

            foreach (var member in instanceMembers)
                EmitInstanceWrapper(sb, member, targetDisplay);

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // v1: skip static-member extensions — C# 14 static extension blocks (`extension(T)` with no
        // parameter name) have compiler restrictions that interact badly with some targets. Revisit later.
        var emittableMembers = type.Members.Where(m => m.Kind is MemberKind.InstanceField or MemberKind.InstanceMethod).ToList();

        // Private `extern static` accessors for the wrappers we emitted
        foreach (var member in emittableMembers)
            EmitAccessor(sb, member, type, targetDisplay);

        sb.AppendLine("}");
    }

    private static void EmitInstanceWrapper(StringBuilder sb, MemberModel member, string targetDisplay)
    {
        var accessorName = AccessorName(member);

        if (member.Kind == MemberKind.InstanceField)
        {
            var refKind = "ref "; // fields always come back as ref so the caller can read and write
            sb.Append("        public ").Append(refKind).Append(member.ReturnTypeSignature).Append(' ').Append(member.WrapperName)
              .Append(" { ").Append(Inlining).Append(" get => ref ").Append(accessorName).AppendLine("(@this); }");
            return;
        }

        // Instance method
        var returnPrefix = member.IsVoidReturn() ? "void" : (member.ReturnsByRef ? "ref " : "") + member.ReturnTypeSignature;
        var wrapperParams = FormatParams(member, includeSelf: false);
        var callArgs = FormatCallArgs(member, "@this");

        sb.Append("        ").Append(Inlining).AppendLine();
        sb.Append("        public ");
        if (member.MethodTypeParameters.Count > 0)
        {
            // Method-level generics go before the name; they conflict only if they duplicate type-level.
        }
        sb.Append(returnPrefix).Append(' ').Append(member.WrapperName);
        if (member.MethodTypeParameters.Count > 0)
            sb.Append('<').Append(string.Join(", ", member.MethodTypeParameters)).Append('>');
        sb.Append('(').Append(wrapperParams).Append(')');
        sb.Append(" => ");
        if (member.ReturnsByRef) sb.Append("ref ");
        sb.Append(accessorName).Append('(').Append(callArgs).AppendLine(");");
    }

    private static void EmitStaticWrapper(StringBuilder sb, MemberModel member, string targetDisplay)
    {
        var accessorName = AccessorName(member);
        string selfDefault = "default(" + targetDisplay + ")!";

        if (member.Kind == MemberKind.StaticField)
        {
            sb.Append("        public static ref ").Append(member.ReturnTypeSignature).Append(' ').Append(member.WrapperName)
              .Append(" { ").Append(Inlining).Append(" get => ref ").Append(accessorName).Append('(').Append(selfDefault).AppendLine("); }");
            return;
        }

        // Static method
        var returnPrefix = member.IsVoidReturn() ? "void" : (member.ReturnsByRef ? "ref " : "") + member.ReturnTypeSignature;
        var wrapperParams = FormatParams(member, includeSelf: false);
        var callArgs = FormatCallArgs(member, selfDefault);

        sb.Append("        ").Append(Inlining).AppendLine();
        sb.Append("        public static ").Append(returnPrefix).Append(' ').Append(member.WrapperName);
        if (member.MethodTypeParameters.Count > 0)
            sb.Append('<').Append(string.Join(", ", member.MethodTypeParameters)).Append('>');
        sb.Append('(').Append(wrapperParams).Append(')');
        sb.Append(" => ");
        if (member.ReturnsByRef) sb.Append("ref ");
        sb.Append(accessorName).Append('(').Append(callArgs).AppendLine(");");
    }

    private static void EmitAccessor(StringBuilder sb, MemberModel member, TypeModel type, string targetDisplay)
    {
        var accessorName = AccessorName(member);
        string kindLiteral = member.Kind switch
        {
            MemberKind.InstanceField => "global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field",
            MemberKind.StaticField => "global::System.Runtime.CompilerServices.UnsafeAccessorKind.StaticField",
            MemberKind.InstanceMethod => "global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method",
            MemberKind.StaticMethod => "global::System.Runtime.CompilerServices.UnsafeAccessorKind.StaticMethod",
            _ => "global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field",
        };

        sb.Append("    [global::System.Runtime.CompilerServices.UnsafeAccessor(")
          .Append(kindLiteral).Append(", Name = \"").Append(member.Name).AppendLine("\")]");

        sb.Append("    private static extern ");

        switch (member.Kind)
        {
            case MemberKind.InstanceField:
                sb.Append("ref ").Append(member.ReturnTypeSignature).Append(' ').Append(accessorName);
                EmitGenericClause(sb, type.TypeParameterNames);
                sb.Append('(').Append(targetDisplay).Append(" @this)");
                AppendConstraints(sb, type.TypeParameterConstraints);
                sb.AppendLine(";");
                break;

            case MemberKind.StaticField:
                sb.Append("ref ").Append(member.ReturnTypeSignature).Append(' ').Append(accessorName);
                EmitGenericClause(sb, type.TypeParameterNames);
                // Static field UnsafeAccessor requires a dummy first parameter of the type.
                sb.Append('(').Append(targetDisplay).AppendLine(" @this);");
                break;

            case MemberKind.InstanceMethod:
                {
                    var returnPrefix = member.IsVoidReturn() ? "void" : (member.ReturnsByRef ? "ref " : "") + member.ReturnTypeSignature;
                    sb.Append(returnPrefix).Append(' ').Append(accessorName);
                    EmitGenericClause(sb, MergeTypeParams(type.TypeParameterNames, member.MethodTypeParameters));
                    sb.Append('(').Append(targetDisplay).Append(" @this");
                    AppendParams(sb, member, leadingComma: true);
                    sb.Append(")");
                    AppendConstraints(sb, type.TypeParameterConstraints);
                    sb.AppendLine(";");
                }
                break;

            case MemberKind.StaticMethod:
                {
                    var returnPrefix = member.IsVoidReturn() ? "void" : (member.ReturnsByRef ? "ref " : "") + member.ReturnTypeSignature;
                    sb.Append(returnPrefix).Append(' ').Append(accessorName);
                    EmitGenericClause(sb, MergeTypeParams(type.TypeParameterNames, member.MethodTypeParameters));
                    sb.Append('(').Append(targetDisplay).Append(" @this");
                    AppendParams(sb, member, leadingComma: true);
                    sb.AppendLine(");");
                }
                break;
        }

        sb.AppendLine();
    }

    private static void EmitGenericClause(StringBuilder sb, IReadOnlyList<string> typeParams)
    {
        if (typeParams.Count == 0) return;
        sb.Append('<').Append(string.Join(", ", typeParams)).Append('>');
    }

    private static void AppendConstraints(StringBuilder sb, IReadOnlyList<string> constraints)
    {
        foreach (var c in constraints)
            if (!string.IsNullOrEmpty(c)) sb.Append(' ').Append(c);
    }

    private static IReadOnlyList<string> MergeTypeParams(IReadOnlyList<string> outer, IReadOnlyList<string> inner)
    {
        if (inner.Count == 0) return outer;
        if (outer.Count == 0) return inner;
        var merged = new List<string>(outer.Count + inner.Count);
        merged.AddRange(outer);
        merged.AddRange(inner);
        return merged;
    }

    private static string FormatParams(MemberModel member, bool includeSelf)
    {
        var sb = new StringBuilder();
        bool first = !includeSelf;
        if (includeSelf)
        {
            sb.Append("@this");
            first = false;
        }
        foreach (var p in member.Parameters)
        {
            if (!first) sb.Append(", ");
            switch (p.RefKind)
            {
                case ParamRefKind.Ref: sb.Append("ref "); break;
                case ParamRefKind.Out: sb.Append("out "); break;
                case ParamRefKind.In: sb.Append("in "); break;
                case ParamRefKind.RefReadonly: sb.Append("ref readonly "); break;
            }
            sb.Append(p.TypeSignature).Append(' ').Append(EscapeIdentifier(p.Name));
            first = false;
        }
        return sb.ToString();
    }

    private static string FormatCallArgs(MemberModel member, string? selfArg)
    {
        var sb = new StringBuilder();
        if (selfArg is not null) sb.Append(selfArg);
        bool first = selfArg is null;
        foreach (var p in member.Parameters)
        {
            if (!first) sb.Append(", ");
            switch (p.RefKind)
            {
                case ParamRefKind.Ref: sb.Append("ref "); break;
                case ParamRefKind.Out: sb.Append("out "); break;
                case ParamRefKind.In: sb.Append("in "); break;
                case ParamRefKind.RefReadonly: sb.Append("in "); break;
            }
            sb.Append(EscapeIdentifier(p.Name));
            first = false;
        }
        return sb.ToString();
    }

    private static void AppendParams(StringBuilder sb, MemberModel member, bool leadingComma)
    {
        foreach (var p in member.Parameters)
        {
            if (leadingComma) sb.Append(", ");
            switch (p.RefKind)
            {
                case ParamRefKind.Ref: sb.Append("ref "); break;
                case ParamRefKind.Out: sb.Append("out "); break;
                case ParamRefKind.In: sb.Append("in "); break;
                case ParamRefKind.RefReadonly: sb.Append("ref readonly "); break;
            }
            sb.Append(p.TypeSignature).Append(' ').Append(EscapeIdentifier(p.Name));
            leadingComma = true;
        }
    }

    private static string AccessorName(MemberModel member)
    {
        // Always prefix with __pnet to keep the raw accessor name distinct from user-facing p_ names.
        var n = member.Name;
        var sb = new StringBuilder("__pnet_");
        foreach (var c in n) sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        return sb.ToString();
    }

    private static string EscapeIdentifier(string name)
    {
        // Very conservative escaper — avoid C# keywords.
        switch (name)
        {
            case "this": case "base": case "out": case "ref": case "in": case "params":
            case "null": case "default": case "void": case "new": case "return":
            case "class": case "struct": case "interface": case "enum":
            case "static": case "public": case "private": case "internal": case "protected":
            case "if": case "else": case "for": case "while": case "do": case "switch":
            case "case": case "break": case "continue": case "try": case "catch": case "finally":
            case "throw": case "using": case "namespace": case "value": case "object":
            case "string": case "int": case "long": case "short": case "byte": case "bool":
            case "double": case "float": case "decimal": case "char": case "uint": case "ulong":
            case "ushort": case "sbyte":
                return "@" + name;
            default:
                return name;
        }
    }

    internal static bool IsVoidReturn(this MemberModel m) => m.ReturnsVoid;
}
